import { MatrixData } from "./types/matrix";
import MatrixView from "./components/MatrixView";
import fs from "fs";
import path from "path";

async function getMatrixData(): Promise<MatrixData> {
  const filePath = path.join(process.cwd(), "public", "data", "matrix.json");
  const data = fs.readFileSync(filePath, "utf-8");
  return JSON.parse(data);
}

export default async function Home() {
  const data = await getMatrixData();
  const missingTools = data.build_metadata?.missing_tools ?? [];

  return (
    <main className="min-h-screen">
      <header className="border-b border-gray-800 bg-gray-900/50 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-[1600px] mx-auto px-4 py-4">
          <h1 className="text-2xl font-bold">
            <span className="text-green-400">Can I Use:</span>{" "}
            <span className="text-white">Parquet</span>
          </h1>
          <p className="text-gray-400 text-sm mt-1">
            Parquet format compatibility matrix — verified by running actual tests against each library version
          </p>
        </div>
      </header>
      {missingTools.length > 0 && (
        <div className="bg-yellow-900/60 border-b border-yellow-700 text-yellow-200 text-sm px-4 py-3">
          <div className="max-w-[1600px] mx-auto">
            ⚠️ <strong>Partial data:</strong> Some tools could not be tested in the last CI run and are missing from this matrix:{" "}
            <span className="font-mono">{missingTools.join(", ")}</span>.
            Results shown may be incomplete.
          </div>
        </div>
      )}
      <div className="max-w-[1600px] mx-auto px-4 py-6">
        <MatrixView data={data} />
      </div>
      <footer className="border-t border-gray-800 mt-12 py-6 text-center text-gray-500 text-sm">
        <p>
          Data generated by running CLI tests against each library.{" "}
          <a
            href="https://github.com/Kuinox/CanIUseParquet"
            className="text-green-400 hover:underline"
          >
            View source & methodology
          </a>
        </p>
      </footer>
    </main>
  );
}
