import Link from "next/link";
import { getMatrixData } from "./lib/server";
import {
  CATEGORY_LABELS,
  CATEGORY_DESCRIPTIONS,
  CATEGORY_TO_SLUG,
  getCategoryFeatures,
  InternalCategory,
} from "./lib/data";

export default async function Home() {
  const data = getMatrixData();
  const missingTools = data.build_metadata?.missing_tools ?? [];
  const toolIds = Object.keys(data.tools);
  const categories = Object.keys(CATEGORY_TO_SLUG) as InternalCategory[];

  return (
    <main className="min-h-screen">
      {missingTools.length > 0 && (
        <div className="bg-yellow-900/60 border-b border-yellow-700 text-yellow-200 text-sm px-4 py-3">
          <div className="max-w-[1600px] mx-auto">
            ⚠️ <strong>Partial data:</strong> Some tools could not be tested in
            the last CI run and are missing from this matrix:{" "}
            <span className="font-mono">{missingTools.join(", ")}</span>.
            Results shown may be incomplete.
          </div>
        </div>
      )}

      <div className="max-w-[1600px] mx-auto px-4 py-10">
        {/* Hero */}
        <div className="mb-12 text-center">
          <h2 className="text-4xl font-bold text-white mb-4">
            Parquet Compatibility Matrix
          </h2>
          <p className="text-gray-400 text-lg max-w-2xl mx-auto">
            Verified compatibility data for Parquet features across libraries
            and query engines — generated by running actual tests against each
            version.
          </p>
        </div>

        {/* Browse by Category */}
        <section className="mb-12">
          <h2 className="text-2xl font-semibold text-white mb-6">
            Browse by Category
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {categories.map((cat) => {
              const slug = CATEGORY_TO_SLUG[cat];
              const featureCount = getCategoryFeatures(data, cat).length;
              return (
                <Link
                  key={cat}
                  href={`/${slug}`}
                  className="group block bg-gray-900 border border-gray-800 rounded-xl p-6 hover:border-green-700 hover:bg-gray-900/80 transition-all"
                >
                  <h3 className="text-lg font-semibold text-white mb-2 group-hover:text-green-400 transition-colors">
                    {CATEGORY_LABELS[cat]}
                  </h3>
                  <p className="text-gray-400 text-sm mb-4">
                    {CATEGORY_DESCRIPTIONS[cat]}
                  </p>
                  <span className="text-xs text-gray-500 font-mono">
                    {featureCount} feature{featureCount !== 1 ? "s" : ""}
                  </span>
                </Link>
              );
            })}
          </div>
        </section>

        {/* Tools Overview */}
        <section className="mb-12">
          <h2 className="text-2xl font-semibold text-white mb-6">
            Tested Libraries
          </h2>
          <div className="overflow-x-auto rounded-lg border border-gray-800">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-900">
                  <th className="px-4 py-3 text-left text-gray-300 font-medium">
                    Tool
                  </th>
                  <th className="px-4 py-3 text-left text-gray-300 font-medium">
                    Language
                  </th>
                  <th className="px-4 py-3 text-left text-gray-300 font-medium">
                    Latest Version
                  </th>
                  <th className="px-4 py-3 text-left text-gray-300 font-medium">
                    Versions Tested
                  </th>
                </tr>
              </thead>
              <tbody>
                {toolIds.map((tid, i) => (
                  <tr
                    key={tid}
                    className={i % 2 === 0 ? "bg-gray-900/50" : "bg-gray-950"}
                  >
                    <td className="px-4 py-3 font-semibold text-white">
                      {data.tools[tid].display_name}
                    </td>
                    <td className="px-4 py-3 text-gray-400">
                      {data.tools[tid].language}
                    </td>
                    <td className="px-4 py-3 font-mono text-green-400">
                      {data.tools[tid].latest_version}
                    </td>
                    <td className="px-4 py-3 font-mono text-gray-500 text-xs">
                      {data.tools[tid].tested_versions.join(", ")}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      </div>

      <footer className="border-t border-gray-800 mt-12 py-6 text-center text-gray-500 text-sm">
        <p>
          Data generated by running CLI tests against each library.{" "}
          <a
            href="https://github.com/Kuinox/CanIUseParquet"
            className="text-green-400 hover:underline"
          >
            View source &amp; methodology
          </a>
        </p>
      </footer>
    </main>
  );
}
